service: grant

provider:
  name: aws
  runtime: nodejs12.x
  region: us-west-2
  stage: grant

functions:
  dynamic-state:
    handler: grant/grant.handler
    events:
      - http:
          path: /grant/{path+}
          method: ANY

plugins:
  - serverless-offline

custom:
  serverless-offline:
    port: 3000
    noPrependStageInUrl: true
